apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: gotest1227
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gotest1227 
  name: gotest1227
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: gotest1227
    weight: 100 
