apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gotest1227
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gotest1227 
  name: gotest1227
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: gotest1227 
